[projects]

  # Default project, used when calling serve() or pdf().
  [projects.default]
  homepage_contents = "index"

  metadata_path = "metadata.yml"

  contents = [
    "introduction",
    "analysis",
    "references"
  ]

  # Output pdf or docx filename.
  output_filename = "analysis"

  # Prefix for GitHub or GitLab Pages.
  online_url_prefix = ""

  # Port used by serve().
  port = 8010

  # For large books, it can be nice to show some information on the homepage
  # which is only visible to online visitors and hidden from book readers (PDF).
  include_homepage_outside_html = false



  # Alternative project, used when calling, for example, serve(project="dev").
  [projects.dev]
  homepage_contents = "index"

  metadata_path = "metadata.yml"

  contents = [
    "introduction",
    "analysis",
    "notes",
    "references"
  ]

  output_filename = "analysis-with-notes"

  port = 8011

  # Extra directories to be copied from the project root into build/.
  extra_directories = [
    "images"
  ]

  include_homepage_outside_html = false
