[projects]

  [projects.default]
  contents = [
    "about",
    "getting-started",
    "demo",
    "references"
  ]
  output_filename = "books"

  # Prefix for GitHub Pages links.
  online_url_prefix = "Books.jl"
