[projects]

  [projects.default]
  contents = [
    "about",
    "getting-started",
    "demo",
    "references"
  ]
  output_filename = "books"

  # Prefix for GitHub Pages links.
  online_url_prefix = "Books.jl"

  # Extra directories to be copied.
  extra_directories = [
    "images"
  ]

  port = 8012

  # The homepage of docs shows some verion info which is nice for the PDF too.
  include_homepage_outside_html = true
