name = "BooksDocs"
uuid = "6b2b467d-d873-4a19-b33c-0abffd8470ba"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "0.1.0"

[deps]
Books = "939d5c6b-51ae-42e7-97ca-7564d0d4ad91"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"

[compat]
CodeTracking = "1.0"
