name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
  workflow_dispatch:

jobs:
  test-and-deploy:
    name: Test and deploy
    runs-on: ${{ matrix.os }}
    permissions: write-all
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
          - "1"
        os:
          - buildjet-2vcpu-ubuntu-2004

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v1

      - name: Install Julia dependencies
        uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        env:
          GKS_ENCODING: "utf8"
          GKSwstype: "100"
